name: Publish

on:
  release:
    types:
      - published
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: build
      run: |
        yarn
        npm run build
    - name: create .npmrc
      run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
      env:
        NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - name: publish
      run: npm publish
